/**
 * typeConfig
 *
 * Módulo de configuración centralizada para los tipos de Pokémon.
 * Define dos recursos principales:
 *
 * 1. types: Mapa de todos los 18 tipos oficiales con su ID numérico
 *    en PokeAPI y su color representativo (colores oficiales de juego).
 *    La función getTypeConfig devuelve el objeto + la URL del sprite
 *    oficial de PokeAPI para Gen IX (Scarlet/Violet).
 *
 * 2. abilityIcons: Mapa de ~180 habilidades a emojis representativos.
 *    Se usa como fallback visual ya que PokeAPI no provee iconos para
 *    habilidades. La función getAbilityIcon busca por nombre (case-insensitive)
 *    y devuelve ⚡ como valor por defecto si no encuentra la habilidad.
 */

const spriteUrl = (id) =>
  `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/types/generation-ix/scarlet-violet/small/${id}.png`

const types = {
  normal:   { id: 1,  color: '#A8A878' },
  fighting: { id: 2,  color: '#C03028' },
  flying:   { id: 3,  color: '#A890F0' },
  poison:   { id: 4,  color: '#A040A0' },
  ground:   { id: 5,  color: '#E0C068' },
  rock:     { id: 6,  color: '#B8A038' },
  bug:      { id: 7,  color: '#A8B820' },
  ghost:    { id: 8,  color: '#705898' },
  steel:    { id: 9,  color: '#B8B8D0' },
  fire:     { id: 10, color: '#F08030' },
  water:    { id: 11, color: '#6890F0' },
  grass:    { id: 12, color: '#78C850' },
  electric: { id: 13, color: '#F8D030' },
  psychic:  { id: 14, color: '#F85888' },
  ice:      { id: 15, color: '#98D8D8' },
  dragon:   { id: 16, color: '#7038F8' },
  dark:     { id: 17, color: '#705848' },
  fairy:    { id: 18, color: '#EE99AC' },
}

export function getTypeConfig(typeName) {
  const found = types[typeName.toLowerCase()]
  return found ? { ...found, icon: spriteUrl(found.id) } : { id: 0, icon: spriteUrl(0), color: '#6b7280' }
}

const abilityIcons = {
  overgrow: '🌿',
  blaze: '🔥',
  torrent: '💧',
  chlorophyll: '☀️',
  'swift swim': '🌊',
  levitate: '🌀',
  intimidate: '😠',
  static: '⚡',
  'cute charm': '🎀',
  guts: '💪',
  'natural cure': '💚',
  pressure: '💢',
  drought: '☀️',
  'sand stream': '🏖️',
  drizzle: '🌧️',
  'snow warning': '❄️',
  'rain dish': '🌧️',
  'shed skin': '🐍',
  'run away': '🏃',
  'keen eye': '👁️',
  'inner focus': '🧘',
  stench: '💨',
  'effect spore': '🍄',
  'liquid ooze': '🧪',
  'poison point': '🧪',
  'shield dust': '🛡️',
  trace: '🔍',
  'huge power': '💪',
  'thick fat': '🛡️',
  'rough skin': '🦔',
  'wonder guard': '🛡️',
  'serene grace': '😇',
  oblivious: '😶',
  'own tempo': '💃',
  'tangled feet': '🦶',
  'motor drive': '⚡',
  'volt absorb': '⚡',
  'water absorb': '💧',
  'flash fire': '🔥',
  'rock head': '🪨',
  sturdy: '🛡️',
  'sand veil': '🏖️',
  'arena trap': '🪤',
  'lightning rod': '⚡',
  'swarm': '🐝',
  'sniper': '🎯',
  'battle armor': '🛡️',
  'compound eyes': '👁️',
  anticipation: '🔮',
  'magic guard': '🛡️',
  'synchronize': '🔄',
  'clear body': '✨',
  insomnia: '😵',
  'shell armor': '🐚',
  'skill link': '🔗',
  'pickup': '🤲',
  'super luck': '🍀',
  'rivalry': '⚔️',
  'steadfast': '🧊',
  'sheer force': '💥',
  adaptability: '🔄',
  'mold breaker': '🔨',
  'unnerve': '😰',
  'defiant': '😤',
  'defeatist': '😟',
  'mummy': '🧟',
  'justified': '⚖️',
  'rattled': '😰',
  'magic bounce': '🪄',
  'sap sipper': '🌿',
  'prankster': '😈',
  'sand rush': '🏖️',
  'wonder skin': '🛡️',
  'analytic': '🧮',
  'illusion': '🪄',
  'imposter': '🎭',
  'infiltrator': '🕵️',
  'moxie': '😤',
  'aftermath': '💥',
  'forewarn': '🔮',
  'frisk': '🔍',
  'poison heal': '💚',
  'toxic boost': '🧪',
  'heatproof': '🛡️',
  'heavy metal': '⚖️',
  'light metal': '🪶',
  'multiscale': '🛡️',
  'harvest': '🌾',
  'telepathy': '🧠',
  'no guard': '👁️',
  'normalize': '🔄',
  'stall': '🐢',
  'technician': '🔧',
  'receiver': '🤲',
  'queenly majesty': '👑',
  'dancer': '💃',
  'battery': '🔋',
  'fluffy': '☁️',
  'dazzling': '✨',
  'disguise': '🎭',
  'schooling': '🐟',
  'merciless': '🗡️',
  'shields down': '🛡️',
  'stakeout': '🕵️',
  'water bubble': '💧',
  'steelworker': '⚙️',
  'berserk': '😡',
  'slush rush': '❄️',
  'tangling hair': '💇',
  'power of alchemy': '🧪',
  'beast boost': '🐉',
  'rks system': '⚙️',
  'electric surge': '⚡',
  'psychic surge': '🔮',
  'misty surge': '💨',
  'grassy surge': '🌿',
  'full metal body': '🛡️',
  'shadow shield': '🛡️',
  'prism armor': '🛡️',
  'neuroforce': '🧠',
  'intrepid sword': '⚔️',
  'dauntless shield': '🛡️',
  'libero': '🔄',
  'ice scales': '❄️',
  'mirror armor': '🪞',
  'gulp missile': '🎯',
  'stalwart': '🛡️',
  'steam engine': '🚂',
  'punk rock': '🎸',
  'sand spit': '🏖️',
  'ice face': '🧊',
  'hunger switch': '🔄',
  'quick draw': '🔫',
  'wandering spirit': '👻',
  'perish body': '💀',
  'curious medicine': '💊',
  'transistor': '⚡',
  "dragon's maw": '🐉',
  'chilling neigh': '🐴',
  'grim neigh': '🐴',
  'as one': '🔗',
  'lingering aroma': '💨',
  'seed sower': '🌱',
  'thermal exchange': '🔥',
  'anger shell': '🐚',
  'purifying salt': '🧂',
  'well-baked body': '🍪',
  'wind rider': '💨',
  'guard dog': '🐕',
  'rocky payload': '🪨',
  'wind power': '💨',
  'zero to hero': '🦸',
  'commander': '🎖️',
  'electromorphosis': '⚡',
  'protosynthesis': '☀️',
  'quark drive': '⚡',
  'good as gold': '🥇',
  'vessel of ruin': '💀',
  'sword of ruin': '⚔️',
  'tablets of ruin': '📜',
  'beads of ruin': '📿',
  'orichalcum pulse': '☀️',
  'hadron engine': '⚡',
  'opportunist': '🎯',
  'cud chew': '🦷',
  'sharpness': '🗡️',
  'supreme overlord': '👑',
  'costar': '⭐',
  'toxic debris': '🧪',
  'armor tailor': '🛡️',
  'earth eater': '🌍',
  'mycelium might': '🍄',
  'hospitality': '🍵',
  'minds eye': '👁️',
  'embody aspect': '✨',
  'tera shift': '💎',
  'unknown': '❓',
}

export function getAbilityIcon(abilityName) {
  return abilityIcons[abilityName.toLowerCase()] || '⚡'
}
